- name: Configure Nginx Web Server
  hosts: webserver
  tasks:
    - name: Copy custom index.html
      copy:
        content: "<h1>Welcome to My Web Server!</h1>"
        dest: /usr/share/nginx/html/index.html

